import React from 'react';
import { Head, Link, usePage } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { 
    Scale, 
    ShieldCheck, 
    CheckCircle2, 
    ArrowLeft, 
    Binary, 
    FileCode2, 
    RotateCcw, 
    Award,
    Eye,
    Cpu
} from 'lucide-react';
import { PageProps } from '@/types';

export default function FairPlay() {
    const { company } = usePage<PageProps>().props;

    return (
        <AppLayout>
            <Head title="Fair Play Policy & RNG Determinism — ChessSkins" />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <div className="mb-10">
                    <Link
                        href="/"
                        className="inline-flex items-center gap-1.5 text-xs font-semibold text-amber-400 hover:text-amber-300 transition mb-4"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        <span>Return to Lobby</span>
                    </Link>
                    <div className="flex items-center gap-3.5">
                        <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-center justify-center shadow-lg shadow-amber-500/10">
                            <Scale className="w-6 h-6" />
                        </div>
                        <div>
                            <h1 className="text-3xl font-black text-white">Fair Play & Engine Determinism</h1>
                            <p className="text-xs text-slate-400 mt-0.5">Mathematical transparency, FIDE rules compliance, and zero server-side manipulation.</p>
                        </div>
                    </div>
                </div>

                <div className="p-8 sm:p-12 rounded-3xl bg-slate-900/80 border border-slate-800 space-y-10 text-sm text-slate-300 leading-relaxed">
                    {/* Key Statement */}
                    <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 flex items-start gap-4">
                        <ShieldCheck className="w-6 h-6 text-emerald-400 shrink-0 mt-1" />
                        <div className="space-y-1">
                            <h2 className="text-base font-bold text-white">Our Fair Play Guarantee</h2>
                            <p className="text-xs text-slate-400 leading-relaxed">
                                At ChessSkins, every move generated by our bot engine and validated on the board is 100% deterministic, 
                                transparent, and fully auditable. We do not employ hidden dynamic handicaps, stealth win-rate throttling, 
                                or algorithmic manipulation. What you see is pure chess logic.
                            </p>
                        </div>
                    </div>

                    {/* Section 1: Standard FIDE Rules */}
                    <section className="space-y-4">
                        <div className="flex items-center gap-2.5 text-white font-bold text-lg">
                            <Award className="w-5 h-5 text-amber-400" />
                            <h3>1. Full Compliance with Official FIDE Rules</h3>
                        </div>
                        <p className="text-xs text-slate-400 leading-relaxed">
                            The ChessSkins engine enforces all standard World Chess Federation (FIDE) Laws of Chess without alteration:
                        </p>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                                <strong className="text-amber-400 block">En Passant Captures</strong>
                                <span className="text-slate-400">Available immediately when an opposing pawn advances two squares past an adjacent pawn.</span>
                            </div>
                            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                                <strong className="text-cyan-400 block">Kingside & Queenside Castling</strong>
                                <span className="text-slate-400">Permitted provided the king and rook have not moved, and squares crossed are not attacked.</span>
                            </div>
                            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                                <strong className="text-emerald-400 block">Pawn Promotion</strong>
                                <span className="text-slate-400">Instant choice of Queen, Rook, Bishop, or Knight upon reaching the 8th rank.</span>
                            </div>
                            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                                <strong className="text-purple-400 block">Draw Conditions</strong>
                                <span className="text-slate-400">Automatic detection of Stalemate, 50-Move Rule, Threefold Repetition, and Insufficient Material.</span>
                            </div>
                        </div>
                    </section>

                    {/* Section 2: Deterministic State Machine */}
                    <section className="space-y-4">
                        <div className="flex items-center gap-2.5 text-white font-bold text-lg">
                            <Binary className="w-5 h-5 text-cyan-400" />
                            <h3>2. Deterministic State Machine vs Random Number Generators (RNG)</h3>
                        </div>
                        <p className="text-xs text-slate-400 leading-relaxed">
                            Unlike gambling sites or loot-box games that depend on opaque random number generators, chess is a game of 
                            complete information. In ChessSkins:
                        </p>
                        <ul className="space-y-2.5 text-xs text-slate-300 list-disc list-inside">
                            <li><strong>Zero RNG in Move Choices:</strong> Scenario bots follow predefined state machine transitions. When the board enters a specified FEN state, the bot executes the calibrated tactical response.</li>
                            <li><strong>Reproducible Game Trajectories:</strong> The exact same moves played by a human against a given scenario will always produce the exact same bot response. You can replay, analyze, and refine your lines with scientific precision.</li>
                            <li><strong>Auditable PGN Logs:</strong> All moves are recorded in standard Portable Game Notation (PGN) format, allowing seamless export into third-party analysis engines like Lichess or Chess.com.</li>
                        </ul>
                    </section>

                    {/* Section 3: Anti-Cheat & Client-Server Integrity */}
                    <section className="space-y-4">
                        <div className="flex items-center gap-2.5 text-white font-bold text-lg">
                            <Cpu className="w-5 h-5 text-emerald-400" />
                            <h3>3. Dual Validation & Anti-Tampering</h3>
                        </div>
                        <p className="text-xs text-slate-400 leading-relaxed">
                            To ensure total integrity and prevent client-side memory tampering:
                        </p>
                        <div className="p-5 rounded-2xl bg-slate-950 border border-slate-800 space-y-3 text-xs">
                            <div className="flex items-start gap-2.5">
                                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                                <span><strong>Dual-Layer Move Legalizer:</strong> Every move is verified on the client via `chess.js` and confirmed by our backend PHP state machine before any reward or progress is recorded.</span>
                            </div>
                            <div className="flex items-start gap-2.5">
                                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                                <span><strong>Immutable Turn Sequencer:</strong> Illegal jumps, piece teleports, or modified piece movements are rejected by the server with immediate state reset.</span>
                            </div>
                            <div className="flex items-start gap-2.5">
                                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                                <span><strong>Rate-Limited Moves:</strong> Bot move endpoints are protected against automated burst manipulation and bot spam.</span>
                            </div>
                        </div>
                    </section>

                    {/* Section 4: Cosmetic Neutrality */}
                    <section className="space-y-4">
                        <div className="flex items-center gap-2.5 text-white font-bold text-lg">
                            <Eye className="w-5 h-5 text-purple-400" />
                            <h3>4. Strict Cosmetic Neutrality Guarantee</h3>
                        </div>
                        <p className="text-xs text-slate-400 leading-relaxed">
                            We believe competitive chess must always remain pure. All piece skins, board themes, and visual styles 
                            sold on ChessSkins provide <strong>zero mechanical advantage</strong>:
                        </p>
                        <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-400 space-y-1.5">
                            <p>• Piece hitboxes and click detection areas are identical across all skins.</p>
                            <p>• Visual animations are lightweight CSS transitions with zero input delay.</p>
                            <p>• Board contrast ratios strictly meet WCAG AA visual accessibility standards so every piece remains unmistakable.</p>
                        </div>
                    </section>

                    <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs">
                        <span className="text-slate-400">Questions about our engine logic or fair play standards?</span>
                        <a
                            href={`mailto:${company?.email || 'info@chess-skins.com'}`}
                            className="text-amber-400 hover:underline font-bold"
                        >
                            Contact Fair Play Officer →
                        </a>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
